[package]
name = "husky-auxies"
version = "1.0.0"
authors= [ "software9119.technology" ]
edition = "2021"
description = "Auxiliary methods for husky implementation."
readme = "./README.md"
homepage = "https://github.com/bravequickcleverfibreyarn/ascii-aide/tree/main/husky-auxies"
repository = "https://github.com/bravequickcleverfibreyarn/ascii-aide/tree/main/husky-auxies"
license = "MIT"
